# Generated by Django 2.2.12 on 2020-07-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
