"""
Django settings for crmdemo project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=@vo$97k*$$)179nvl=fuj0gbgqkz+vt#crn(npb2awqgi(@b*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.web',
    'stark',
    'rbac',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.rbac.RbacMiddleware',  # rbac中间件
]

ROOT_URLCONF = 'crmdemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[
                'django.templatetags.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'crmdemo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crmdemo_db',
        'USER': 'root',
        'PASSWORD': 'xxxx',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# django用户管理配置
AUTH_USER_MODEL = 'web.UserInfo'   # 指定django的用户模型，这样可以使用django自带的用户认证与管理方法
# Authenticaticate函数会同时验证is_active字段，下面语句取消验证
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# rbac用户管理配置
RBAC_USER_MODLE_CLASS = "apps.web.models.UserInfo"  # 用于在rbac分配权限时，读取业务表中的用户信息

# 自动发现URL时，排除的URL
AUTO_DISCOVER_EXCLUDE = [
    '/admin/.*',
    '/login/',
    '/logout/',
]

# 菜单图标列表
ICON_LIST = [
    ['fa-bank','<i class="fa fa-bank"></i>'],
    ['fa-arrows','<i class="fa fa-arrows"></i>'],
    ['fa-automobile','<i class="fa fa-automobile"></i>'],
    ['fa-binoculars','<i class="fa fa-binoculars"></i>'],
    ['fa-calculator','<i class="fa fa-calculator"></i>'],
    ['fa-camera','<i class="fa fa-camera"></i>'],
    ['fa-cube','<i class="fa fa-cube"></i>'],
    ['fa-envelope','<i class="fa fa-envelope"></i>'],
]


# 权限在Session中存储的key
PERMISSION_SESSION_KEY = "permission_url_list_key"
# 菜单在Session中存储的key
MENU_SESSION_KEY = "permission_menu_key"

# 中间件的白名单（无需登录即可访问）
VALID_URL_LIST = [
    '/login/',
    '/admin/.*'
]

# 需要登录但无需权限的URL
NO_PERMISSION_LIST = [
    '/index/',
    '/logout/',
]